name: Java Test with Cucumber and TestNG

on:
  push:
    branches:
      - main  # Trigger only on pushes to the `main` branch (you can change this to your default branch name)

jobs:
  test:
    runs-on: windows-latest  # Use Windows for the test execution environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21 with Temurin
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Use Java 21 for this action
          distribution: 'temurin'  # Use Adoptium Temurin as the JDK distribution

      - name: Set up Google Chrome
        run: |
          choco install googlechrome -y  # Installs the latest version of Google Chrome available on Chocolatey

      - name: Get Chrome Version and Download ChromeDriver
        run: |
          # Try to get the Chrome version from the default installation path
          $chromePath = "C:\Program Files\Google\Chrome\Application\chrome.exe"
          if (-Not (Test-Path $chromePath)) {
            $chromePath = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
          }
          
          if (Test-Path $chromePath) {
            # Get Chrome version by querying the installed Chrome binary
            $chromeVersion = (& $chromePath --version).Split(" ")[1]
            Write-Host "Chrome Version: $chromeVersion"
          
            # Download the corresponding ChromeDriver
            $chromeDriverUrl = "https://chromedriver.storage.googleapis.com/$chromeVersion/chromedriver_win32.zip"
            Write-Host "ChromeDriver URL: $chromeDriverUrl"
          
            # Download and unzip ChromeDriver
            Invoke-WebRequest -Uri $chromeDriverUrl -OutFile chromedriver.zip
            Expand-Archive -Path chromedriver.zip -DestinationPath $env:USERPROFILE\chromedriver
          
            # Add ChromeDriver to PATH
            $env:PATH += ";$env:USERPROFILE\chromedriver"
          } else {
            Write-Host "Chrome is not installed in the default location."
            exit 1  # Exit with error if Chrome is not found
          }

      - name: Install dependencies
        run: |
          mvn install -DskipTests=true  # Install all dependencies and skip tests if needed

      - name: Run tests with Maven
        run: mvn test -Dtest=TestRunner  # Replace TestRunner with your actual test runner class name

