name: Java Test with Cucumber and TestNG

on:
  push:
    branches:
      - main  # Trigger only on pushes to the `main` branch (you can change this to your default branch name)

jobs:
  test:
    runs-on: windows-latest  # Use Windows for the test execution environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21 with Temurin
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Use Java 21 for this action
          distribution: 'temurin'  # Use Adoptium Temurin as the JDK distribution

      - name: Set up Google Chrome
        run: |
          choco install googlechrome -y  # Installs the latest version of Google Chrome available on Chocolatey

      - name: Download ChromeDriver
        run: |
          # Get the current version of Google Chrome installed
          $chromeVersion = (Get-ItemProperty "HKCU:\Software\Google\Chrome\BLBeacon").version
          Write-Host "Chrome Version: $chromeVersion"
          
          # Find the correct ChromeDriver version based on the Chrome version
          $chromeDriverVersion = $chromeVersion.Split('.')[0..2] -join "."  # e.g., "114.0.5735"
          
          # Construct the ChromeDriver download URL
          $chromeDriverUrl = "https://chromedriver.storage.googleapis.com/$chromeDriverVersion/chromedriver_win32.zip"
          Write-Host "ChromeDriver URL: $chromeDriverUrl"
          
          # Download the corresponding ChromeDriver
          Invoke-WebRequest -Uri $chromeDriverUrl -OutFile chromedriver.zip
          Expand-Archive -Path chromedriver.zip -DestinationPath $env:USERPROFILE\chromedriver
          
          # Add the ChromeDriver directory to the PATH
          $env:PATH += ";$env:USERPROFILE\chromedriver"

      - name: Install dependencies
        run: |
          mvn install -DskipTests=true  # Install all dependencies and skip tests if needed

      - name: Run tests with Maven
        run: mvn test -Dtest=TestRunner  # Replace TestRunner with your actual test runner class name

       # Adjust if your test results are elsewhere
