name: Java Test with Cucumber and TestNG

on:
  push:
    branches:
      - main  # Trigger only on pushes to the `main` branch (you can change this to your default branch name)

jobs:
  test:
    runs-on: windows-latest  # Use Windows for the test execution environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Use Java 21 for this action
          distribution: 'temurin'

      - name: Set up Google Chrome
        run: |
          choco install googlechrome -y  # Installs the latest version of Google Chrome available on Chocolatey

      - name: Download ChromeDriver
        run: |
          # Get the latest version of ChromeDriver that corresponds to the latest version of Google Chrome
          $chromeVersion = (Invoke-WebRequest -Uri "https://omahaproxy.appspot.com/all.json" | ConvertFrom-Json | Where-Object { $_.os -eq "win" } | Select-Object -First 1).versions[0].current_version
          Write-Host "Latest Chrome version: $chromeVersion"
          
          # Download the matching version of ChromeDriver
          $driverUrl = "https://chromedriver.storage.googleapis.com/$chromeVersion/chromedriver_win32.zip"
          Invoke-WebRequest -Uri $driverUrl -OutFile chromedriver.zip
          Expand-Archive -Path chromedriver.zip -DestinationPath $env:USERPROFILE\chromedriver
          $env:PATH += ";$env:USERPROFILE\chromedriver"  # Add the chromedriver directory to the PATH

      - name: Install dependencies
        run: |
          mvn install -DskipTests=true  # Install all dependencies and skip tests if needed

      - name: Run tests with Maven
        run: mvn test -Dtest=TestRunner  # Replace TestRunner with your actual test runner class name


