name: Java Test with Cucumber and TestNG

on:
  push:
    branches:
      - main  # Trigger only on pushes to the `main` branch (you can change this to your default branch name)

jobs:
  test:
    runs-on: windows-latest  # Use Windows for the test execution environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21 with Temurin
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Use Java 21 for this action
          distribution: 'temurin'  # Use Adoptium Temurin as the JDK distribution

      - name: Set up Google Chrome
        run: |
          choco install googlechrome -y  # Installs the latest version of Google Chrome available on Chocolatey

      - name: Install ChromeDriver
        run: choco install chromedriver -y

      - name: Install dependencies
        run: |
          mvn install -DskipTests=true  # Install all dependencies and skip tests if needed

      - name: Run tests with Maven
        run: mvn test -Dtest=TestRunner  # Replace TestRunner with your actual test runner class name

      # Check contents of the screenshots directory using Windows command
      - name: List screenshots directory
        if: always()  # Run regardless of whether tests pass or fail
        run: |
          dir screenshots /s
        shell: cmd

      # Step to upload screenshots if tests fail
      - name: Upload screenshots as artifacts
        if: failure()  # Only upload screenshots if the tests fail
        uses: actions/upload-artifact@v2.3.1  # Using specific version number instead of just v3
        with:
          name: screenshot-artifacts
          path: screenshots/**  # This will include all files in the screenshots directory and subdirectories
          retention-days: 5  # Keep the artifacts for 5 days (optional)