name: Java Test with Cucumber and TestNG

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Use Windows for the test execution

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21 with Temurin
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Use Java 21 for this action
          distribution: 'temurin'  # Use Adoptium Temurin as the JDK distribution

      - name: Set up Google Chrome
        run: |
          choco install googlechrome -y  # Installs the latest version of Google Chrome available on Chocolatey

      - name: 🔥 Install ChromeDriver
        run: choco install chromedriver -y

      - name: Install dependencies
        run: |
          mvn install -DskipTests=true  # Install all dependencies and skip tests if needed

      - name: Run tests with Maven
        run: mvn test -Dtest=TestRunner  # Replace TestRunner with your actual test runner class name

      # Check contents of the screenshots directory using Windows command
      - name: List screenshots directory
        if: always()  # Run regardless of whether tests pass or fail
        run: |
          if (Test-Path -Path "screenshots") {
            Get-ChildItem -Path "screenshots" -Recurse | Format-Table FullName, Length, LastWriteTime
            echo "Screenshots directory found, proceeding with artifact preparation"
          } else {
            echo "Screenshots directory not found. Creating empty directory."
            New-Item -ItemType Directory -Path "screenshots"
            echo "Empty file for artifact" | Out-File -FilePath "screenshots/README.txt"
          }
        shell: pwsh

      # Upload the screenshots from the directory as an artifact
      - name: Upload screenshots as artifacts
        if: failure()  # Only upload screenshots if the tests fail
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/*  # This points to the 'screenshots' directory in your repository
